// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '2.3.0';
export const BUILD_NUMBER = '20260718.c2b026c';
export const BUILD_DATE = '18/07/2026';
export const FULL_VERSION = `v${APP_VERSION} (Build ${BUILD_NUMBER})`;
