// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '2.4.1';
export const BUILD_NUMBER = '20260823.1bd5891';
export const BUILD_DATE = '24/08/2026';
export const FULL_VERSION = `v${APP_VERSION} (Build ${BUILD_NUMBER})`;
