const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

try {
  // Read package.json version
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));
  const version = pkg.version || '2.2.0';

  // Get current date/time for build number
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10).replace(/-/g, ''); // e.g., '20260606'
  
  let commitHash = '';
  try {
    commitHash = execSync('git rev-parse --short HEAD').toString().trim();
  } catch (e) {
    // Fallback if git is not available (e.g. in some sandbox builds)
    const hours = String(now.getHours()).padStart(2, '0');
    const minutes = String(now.getMinutes()).padStart(2, '0');
    commitHash = `${hours}${minutes}`;
  }

  const buildNumber = `${dateStr}.${commitHash}`;

  const content = `// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '${version}';
export const BUILD_NUMBER = '${buildNumber}';
export const BUILD_DATE = '${now.toLocaleDateString('id-ID', { year: 'numeric', month: '2-digit', day: '2-digit' })}';
export const FULL_VERSION = \`v\${APP_VERSION} (Build \${BUILD_NUMBER})\`;
`;

  fs.writeFileSync(path.join(__dirname, 'src/lib/version.ts'), content, 'utf8');
  console.log(`✅ Generated version file: v${version} (Build ${buildNumber})`);
} catch (error) {
  console.error('Failed to generate version:', error);
}
