import os
import csv
import glob

folder = r"C:\Users\THINKPAD\.gemini\antigravity\scratch\dashboard-ketapang\public\renstra_dkpp"
out_sql = r"C:\Users\THINKPAD\.gemini\antigravity\scratch\dashboard-ketapang\migrate_renstra_dkpp.sql"

def escape_sql_val(val, col_type='text'):
    if val is None:
        return 'NULL'
    val_str = str(val).strip()
    if val_str == '' or val_str.lower() == 'null':
        return 'NULL'
    if col_type in ('int', 'bigint', 'integer'):
        try:
            return str(int(float(val_str.replace(',', ''))))
        except:
            return 'NULL'
    if col_type == 'numeric':
        try:
            cleaned = val_str.replace(',', '')
            float(cleaned)
            return cleaned
        except:
            return 'NULL'
    # text or varchar or timestamp
    escaped = val_str.replace("'", "''")
    return f"'{escaped}'"

def generate_sql():
    sql_lines = []
    sql_lines.append("-- ==============================================================================")
    sql_lines.append("-- MIGRATION SQL: RENSTRA DKPP & DATA KWT KOTA CILEGON 2026")
    sql_lines.append("-- Generated for Supabase SQL Editor")
    sql_lines.append("-- Includes DDL (CREATE TABLE), RLS Policies, Data Inserts, & Sequence Sync")
    sql_lines.append("-- ==============================================================================\n")

    # 1. DATA KWT CILEGON
    kwt_csv = os.path.join(folder, "data_kwt_cilegon_2026_2026-09-24.csv")
    if os.path.exists(kwt_csv):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 1. TABEL: data_kwt_cilegon (84 Kelompok Wanita Tani se-Kota Cilegon 2026)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."data_kwt_cilegon" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kecamatan" VARCHAR(100),
  "kelurahan" VARCHAR(100),
  "nama_kwt" VARCHAR(255) NOT NULL,
  "nama_ketua" VARCHAR(255),
  "no_wa_ketua" VARCHAR(100),
  "alamat_sekretariat" TEXT,
  "jenis_usaha" TEXT,
  "bantuan" TEXT,
  "status" VARCHAR(50) DEFAULT 'Aktif',
  "latitude" NUMERIC(12, 7),
  "longitude" NUMERIC(12, 7),
  "google_maps" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."data_kwt_cilegon" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read data_kwt_cilegon" ON "public"."data_kwt_cilegon";
CREATE POLICY "Allow anon read data_kwt_cilegon" ON "public"."data_kwt_cilegon" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write data_kwt_cilegon" ON "public"."data_kwt_cilegon";
CREATE POLICY "Allow auth write data_kwt_cilegon" ON "public"."data_kwt_cilegon" FOR ALL USING (true);
""")
        with open(kwt_csv, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        sql_lines.append('INSERT INTO "public"."data_kwt_cilegon" ("id", "no", "kecamatan", "kelurahan", "nama_kwt", "nama_ketua", "no_wa_ketua", "alamat_sekretariat", "jenis_usaha", "bantuan", "status", "latitude", "longitude", "google_maps")')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            # ['No', 'Kecamatan', 'Kelurahan', 'Nama KWT', 'Nama Ketua', 'No WA Ketua', 'Alamat Sekretariat', 'Jenis Usaha', 'Bantuan', 'Status', 'Latitude', 'Longitude', 'Google Maps']
            row_id = escape_sql_val(r[0], 'bigint')
            row_no = escape_sql_val(r[0], 'int')
            kec = escape_sql_val(r[1], 'text')
            kel = escape_sql_val(r[2], 'text')
            kwt = escape_sql_val(r[3], 'text')
            ketua = escape_sql_val(r[4] if len(r) > 4 else None, 'text')
            wa = escape_sql_val(r[5] if len(r) > 5 else None, 'text')
            alamat = escape_sql_val(r[6] if len(r) > 6 else None, 'text')
            usaha = escape_sql_val(r[7] if len(r) > 7 else None, 'text')
            bantuan = escape_sql_val(r[8] if len(r) > 8 else None, 'text')
            status = escape_sql_val(r[9] if len(r) > 9 else 'Aktif', 'text')
            lat = escape_sql_val(r[10] if len(r) > 10 else None, 'numeric')
            lng = escape_sql_val(r[11] if len(r) > 11 else None, 'numeric')
            gmaps = escape_sql_val(r[12] if len(r) > 12 else None, 'text')
            value_chunks.append(f"  ({row_id}, {row_no}, {kec}, {kel}, {kwt}, {ketua}, {wa}, {alamat}, {usaha}, {bantuan}, {status}, {lat}, {lng}, {gmaps})")
        
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kecamatan" = EXCLUDED."kecamatan",
  "kelurahan" = EXCLUDED."kelurahan",
  "nama_kwt" = EXCLUDED."nama_kwt",
  "nama_ketua" = EXCLUDED."nama_ketua",
  "no_wa_ketua" = EXCLUDED."no_wa_ketua",
  "alamat_sekretariat" = EXCLUDED."alamat_sekretariat",
  "jenis_usaha" = EXCLUDED."jenis_usaha",
  "bantuan" = EXCLUDED."bantuan",
  "status" = EXCLUDED."status",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "google_maps" = EXCLUDED."google_maps";

SELECT setval(pg_get_serial_sequence('"public"."data_kwt_cilegon"', 'id'), coalesce(max("id"), 1)) FROM "public"."data_kwt_cilegon";
\n""")

    # 2. RENSTRA TUJUAN SASARAN
    f_path = os.path.join(folder, "renstra_tujuan_sasaran_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 2. TABEL: renstra_tujuan_sasaran (Tujuan & Sasaran Renstra DKPP Cilegon)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_tujuan_sasaran" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "nspk_sasaran_rpjmd" TEXT,
  "tujuan" TEXT,
  "sasaran_pd" TEXT,
  "indikator_sasaran" TEXT,
  "satuan" VARCHAR(50),
  "baseline_2024" VARCHAR(50),
  "target_2025" VARCHAR(50),
  "target_2026" VARCHAR(50),
  "target_2027" VARCHAR(50),
  "target_2028" VARCHAR(50),
  "target_2029" VARCHAR(50),
  "target_2030" VARCHAR(50),
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_tujuan_sasaran" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_tujuan_sasaran" ON "public"."renstra_tujuan_sasaran";
CREATE POLICY "Allow anon read renstra_tujuan_sasaran" ON "public"."renstra_tujuan_sasaran" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_tujuan_sasaran" ON "public"."renstra_tujuan_sasaran";
CREATE POLICY "Allow auth write renstra_tujuan_sasaran" ON "public"."renstra_tujuan_sasaran" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'no', 'nspk_sasaran_rpjmd', 'tujuan', 'sasaran_pd', 'indikator_sasaran', 'satuan', 'baseline_2024', 'target_2025', 'target_2026', 'target_2027', 'target_2028', 'target_2029', 'target_2030', 'keterangan']
        sql_lines.append('INSERT INTO "public"."renstra_tujuan_sasaran" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_no = escape_sql_val(r[1], 'int')
            v_vals = [v_id, v_no] + [escape_sql_val(r[idx], 'text') for idx in range(2, 15)]
            value_chunks.append(f"  ({', '.join(v_vals)})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "nspk_sasaran_rpjmd" = EXCLUDED."nspk_sasaran_rpjmd",
  "tujuan" = EXCLUDED."tujuan",
  "sasaran_pd" = EXCLUDED."sasaran_pd",
  "indikator_sasaran" = EXCLUDED."indikator_sasaran",
  "satuan" = EXCLUDED."satuan",
  "baseline_2024" = EXCLUDED."baseline_2024",
  "target_2025" = EXCLUDED."target_2025",
  "target_2026" = EXCLUDED."target_2026",
  "target_2027" = EXCLUDED."target_2027",
  "target_2028" = EXCLUDED."target_2028",
  "target_2029" = EXCLUDED."target_2029",
  "target_2030" = EXCLUDED."target_2030",
  "keterangan" = EXCLUDED."keterangan";

SELECT setval(pg_get_serial_sequence('"public"."renstra_tujuan_sasaran"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_tujuan_sasaran";
\n""")

    # 3. RENSTRA IKU
    f_path = os.path.join(folder, "renstra_iku_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 3. TABEL: renstra_iku (Indikator Kinerja Utama Renstra DKPP Cilegon)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_iku" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kode_skpd" VARCHAR(100),
  "nama_skpd" VARCHAR(255),
  "indikator" TEXT,
  "satuan" VARCHAR(50),
  "baseline_2024" VARCHAR(50),
  "target_2025" VARCHAR(50),
  "target_2026" VARCHAR(50),
  "target_2027" VARCHAR(50),
  "target_2028" VARCHAR(50),
  "target_2029" VARCHAR(50),
  "target_2030" VARCHAR(50),
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_iku" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_iku" ON "public"."renstra_iku";
CREATE POLICY "Allow anon read renstra_iku" ON "public"."renstra_iku" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_iku" ON "public"."renstra_iku";
CREATE POLICY "Allow auth write renstra_iku" ON "public"."renstra_iku" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'no', 'kode_skpd', 'nama_skpd', 'indikator', 'satuan', 'baseline_2024', 'target_2025', 'target_2026', 'target_2027', 'target_2028', 'target_2029', 'target_2030', 'keterangan']
        sql_lines.append('INSERT INTO "public"."renstra_iku" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_no = escape_sql_val(r[1], 'int')
            v_vals = [v_id, v_no] + [escape_sql_val(r[idx], 'text') for idx in range(2, 14)]
            value_chunks.append(f"  ({', '.join(v_vals)})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kode_skpd" = EXCLUDED."kode_skpd",
  "nama_skpd" = EXCLUDED."nama_skpd",
  "indikator" = EXCLUDED."indikator",
  "satuan" = EXCLUDED."satuan",
  "baseline_2024" = EXCLUDED."baseline_2024",
  "target_2025" = EXCLUDED."target_2025",
  "target_2026" = EXCLUDED."target_2026",
  "target_2027" = EXCLUDED."target_2027",
  "target_2028" = EXCLUDED."target_2028",
  "target_2029" = EXCLUDED."target_2029",
  "target_2030" = EXCLUDED."target_2030",
  "keterangan" = EXCLUDED."keterangan";

SELECT setval(pg_get_serial_sequence('"public"."renstra_iku"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_iku";
\n""")

    # 4. RENSTRA IKD
    f_path = os.path.join(folder, "renstra_ikd_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 4. TABEL: renstra_ikd (Indikator Kinerja Daerah Renstra DKPP Cilegon)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_ikd" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "urusan_pd" VARCHAR(255),
  "indikator" TEXT,
  "satuan" VARCHAR(50),
  "baseline_2024" VARCHAR(50),
  "target_2025" VARCHAR(50),
  "target_2026" VARCHAR(50),
  "target_2027" VARCHAR(50),
  "target_2028" VARCHAR(50),
  "target_2029" VARCHAR(50),
  "target_2030" VARCHAR(50),
  "perangkat_daerah" VARCHAR(255),
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_ikd" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_ikd" ON "public"."renstra_ikd";
CREATE POLICY "Allow anon read renstra_ikd" ON "public"."renstra_ikd" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_ikd" ON "public"."renstra_ikd";
CREATE POLICY "Allow auth write renstra_ikd" ON "public"."renstra_ikd" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'no', 'urusan_pd', 'indikator', 'satuan', 'baseline_2024', 'target_2025', 'target_2026', 'target_2027', 'target_2028', 'target_2029', 'target_2030', 'perangkat_daerah']
        sql_lines.append('INSERT INTO "public"."renstra_ikd" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_no = escape_sql_val(r[1], 'int')
            v_vals = [v_id, v_no] + [escape_sql_val(r[idx], 'text') for idx in range(2, 13)]
            value_chunks.append(f"  ({', '.join(v_vals)})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "urusan_pd" = EXCLUDED."urusan_pd",
  "indikator" = EXCLUDED."indikator",
  "satuan" = EXCLUDED."satuan",
  "baseline_2024" = EXCLUDED."baseline_2024",
  "target_2025" = EXCLUDED."target_2025",
  "target_2026" = EXCLUDED."target_2026",
  "target_2027" = EXCLUDED."target_2027",
  "target_2028" = EXCLUDED."target_2028",
  "target_2029" = EXCLUDED."target_2029",
  "target_2030" = EXCLUDED."target_2030",
  "perangkat_daerah" = EXCLUDED."perangkat_daerah";

SELECT setval(pg_get_serial_sequence('"public"."renstra_ikd"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_ikd";
\n""")

    # 5. RENSTRA IKK
    f_path = os.path.join(folder, "renstra_ikk_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 5. TABEL: renstra_ikk (Indikator Kinerja Kunci Renstra DKPP Cilegon)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_ikk" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kode_urusan_pd" VARCHAR(50),
  "nama_urusan_pd" VARCHAR(255),
  "no_urut" INTEGER,
  "indikator" TEXT,
  "status" VARCHAR(50),
  "satuan" VARCHAR(50),
  "baseline_2024" VARCHAR(50),
  "target_2025" VARCHAR(50),
  "target_2026" VARCHAR(50),
  "target_2027" VARCHAR(50),
  "target_2028" VARCHAR(50),
  "target_2029" VARCHAR(50),
  "target_2030" VARCHAR(50),
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_ikk" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_ikk" ON "public"."renstra_ikk";
CREATE POLICY "Allow anon read renstra_ikk" ON "public"."renstra_ikk" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_ikk" ON "public"."renstra_ikk";
CREATE POLICY "Allow auth write renstra_ikk" ON "public"."renstra_ikk" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'kode_urusan_pd', 'nama_urusan_pd', 'no_urut', 'indikator', 'status', 'satuan', 'baseline_2024', 'target_2025', 'target_2026', 'target_2027', 'target_2028', 'target_2029', 'target_2030', 'keterangan']
        sql_lines.append('INSERT INTO "public"."renstra_ikk" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_kode = escape_sql_val(r[1], 'text')
            v_nama = escape_sql_val(r[2], 'text')
            v_no = escape_sql_val(r[3], 'int')
            v_vals = [v_id, v_kode, v_nama, v_no] + [escape_sql_val(r[idx], 'text') for idx in range(4, 15)]
            value_chunks.append(f"  ({', '.join(v_vals)})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "kode_urusan_pd" = EXCLUDED."kode_urusan_pd",
  "nama_urusan_pd" = EXCLUDED."nama_urusan_pd",
  "no_urut" = EXCLUDED."no_urut",
  "indikator" = EXCLUDED."indikator",
  "status" = EXCLUDED."status",
  "satuan" = EXCLUDED."satuan",
  "baseline_2024" = EXCLUDED."baseline_2024",
  "target_2025" = EXCLUDED."target_2025",
  "target_2026" = EXCLUDED."target_2026",
  "target_2027" = EXCLUDED."target_2027",
  "target_2028" = EXCLUDED."target_2028",
  "target_2029" = EXCLUDED."target_2029",
  "target_2030" = EXCLUDED."target_2030",
  "keterangan" = EXCLUDED."keterangan";

SELECT setval(pg_get_serial_sequence('"public"."renstra_ikk"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_ikk";
\n""")

    # 6. RENSTRA CASCADING PROGRAM
    f_path = os.path.join(folder, "renstra_cascading_program_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 6. TABEL: renstra_cascading_program (Cascading Target & Pagu Anggaran 2025-2030)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_cascading_program" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tujuan" TEXT,
  "sasaran" TEXT,
  "indikator_sasaran" TEXT,
  "program" TEXT,
  "indikator_program" TEXT,
  "satuan" VARCHAR(50),
  "target_baseline_2024" VARCHAR(50),
  "target_2025" VARCHAR(50),
  "pagu_2025" NUMERIC(20, 2),
  "target_2026" VARCHAR(50),
  "pagu_2026" NUMERIC(20, 2),
  "target_2027" VARCHAR(50),
  "pagu_2027" NUMERIC(20, 2),
  "target_2028" VARCHAR(50),
  "pagu_2028" NUMERIC(20, 2),
  "target_2029" VARCHAR(50),
  "pagu_2029" NUMERIC(20, 2),
  "target_2030" VARCHAR(50),
  "unit_penanggung_jawab" VARCHAR(255),
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_cascading_program" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_cascading_program" ON "public"."renstra_cascading_program";
CREATE POLICY "Allow anon read renstra_cascading_program" ON "public"."renstra_cascading_program" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_cascading_program" ON "public"."renstra_cascading_program";
CREATE POLICY "Allow auth write renstra_cascading_program" ON "public"."renstra_cascading_program" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'tujuan', 'sasaran', 'indikator_sasaran', 'program', 'indikator_program', 'satuan', 'target_baseline_2024', 'target_2025', 'pagu_2025', 'target_2026', 'pagu_2026', 'target_2027', 'pagu_2027', 'target_2028', 'pagu_2028', 'target_2029', 'pagu_2029', 'target_2030', 'unit_penanggung_jawab']
        sql_lines.append('INSERT INTO "public"."renstra_cascading_program" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_tujuan = escape_sql_val(r[1], 'text')
            v_sasaran = escape_sql_val(r[2], 'text')
            v_indsas = escape_sql_val(r[3], 'text')
            v_prog = escape_sql_val(r[4], 'text')
            v_indprog = escape_sql_val(r[5], 'text')
            v_sat = escape_sql_val(r[6], 'text')
            v_tb24 = escape_sql_val(r[7], 'text')
            v_t25 = escape_sql_val(r[8], 'text')
            v_p25 = escape_sql_val(r[9], 'numeric')
            v_t26 = escape_sql_val(r[10], 'text')
            v_p26 = escape_sql_val(r[11], 'numeric')
            v_t27 = escape_sql_val(r[12], 'text')
            v_p27 = escape_sql_val(r[13], 'numeric')
            v_t28 = escape_sql_val(r[14], 'text')
            v_p28 = escape_sql_val(r[15], 'numeric')
            v_t29 = escape_sql_val(r[16], 'text')
            v_p29 = escape_sql_val(r[17], 'numeric')
            v_t30 = escape_sql_val(r[18], 'text')
            v_unit = escape_sql_val(r[19], 'text')
            value_chunks.append(f"  ({v_id}, {v_tujuan}, {v_sasaran}, {v_indsas}, {v_prog}, {v_indprog}, {v_sat}, {v_tb24}, {v_t25}, {v_p25}, {v_t26}, {v_p26}, {v_t27}, {v_p27}, {v_t28}, {v_p28}, {v_t29}, {v_p29}, {v_t30}, {v_unit})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "tujuan" = EXCLUDED."tujuan",
  "sasaran" = EXCLUDED."sasaran",
  "indikator_sasaran" = EXCLUDED."indikator_sasaran",
  "program" = EXCLUDED."program",
  "indikator_program" = EXCLUDED."indikator_program",
  "satuan" = EXCLUDED."satuan",
  "target_baseline_2024" = EXCLUDED."target_baseline_2024",
  "target_2025" = EXCLUDED."target_2025",
  "pagu_2025" = EXCLUDED."pagu_2025",
  "target_2026" = EXCLUDED."target_2026",
  "pagu_2026" = EXCLUDED."pagu_2026",
  "target_2027" = EXCLUDED."target_2027",
  "pagu_2027" = EXCLUDED."pagu_2027",
  "target_2028" = EXCLUDED."target_2028",
  "pagu_2028" = EXCLUDED."pagu_2028",
  "target_2029" = EXCLUDED."target_2029",
  "pagu_2029" = EXCLUDED."pagu_2029",
  "target_2030" = EXCLUDED."target_2030",
  "unit_penanggung_jawab" = EXCLUDED."unit_penanggung_jawab";

SELECT setval(pg_get_serial_sequence('"public"."renstra_cascading_program"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_cascading_program";
\n""")

    # 7. RENSTRA SUBKEGIATAN PRIORITAS
    f_path = os.path.join(folder, "renstra_subkegiatan_prioritas_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 7. TABEL: renstra_subkegiatan_prioritas (Subkegiatan Prioritas Daerah DKPP)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_subkegiatan_prioritas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kode_skpd" VARCHAR(100),
  "nama_skpd" VARCHAR(255),
  "kode_program" VARCHAR(50),
  "nama_program" VARCHAR(255),
  "outcome" TEXT,
  "kode_kegiatan" VARCHAR(50),
  "nama_kegiatan" VARCHAR(255),
  "kode_subkegiatan" VARCHAR(50),
  "nama_subkegiatan" VARCHAR(255),
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_subkegiatan_prioritas" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_subkegiatan_prioritas" ON "public"."renstra_subkegiatan_prioritas";
CREATE POLICY "Allow anon read renstra_subkegiatan_prioritas" ON "public"."renstra_subkegiatan_prioritas" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_subkegiatan_prioritas" ON "public"."renstra_subkegiatan_prioritas";
CREATE POLICY "Allow auth write renstra_subkegiatan_prioritas" ON "public"."renstra_subkegiatan_prioritas" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'no', 'kode_skpd', 'nama_skpd', 'kode_program', 'nama_program', 'outcome', 'kode_kegiatan', 'nama_kegiatan', 'kode_subkegiatan', 'nama_subkegiatan', 'keterangan']
        sql_lines.append('INSERT INTO "public"."renstra_subkegiatan_prioritas" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
        sql_lines.append('VALUES')
        value_chunks = []
        for r in rows:
            v_id = escape_sql_val(r[0], 'bigint')
            v_no = escape_sql_val(r[1], 'int')
            v_vals = [v_id, v_no] + [escape_sql_val(r[idx], 'text') for idx in range(2, 12)]
            value_chunks.append(f"  ({', '.join(v_vals)})")
        sql_lines.append(",\n".join(value_chunks))
        sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kode_skpd" = EXCLUDED."kode_skpd",
  "nama_skpd" = EXCLUDED."nama_skpd",
  "kode_program" = EXCLUDED."kode_program",
  "nama_program" = EXCLUDED."nama_program",
  "outcome" = EXCLUDED."outcome",
  "kode_kegiatan" = EXCLUDED."kode_kegiatan",
  "nama_kegiatan" = EXCLUDED."nama_kegiatan",
  "kode_subkegiatan" = EXCLUDED."kode_subkegiatan",
  "nama_subkegiatan" = EXCLUDED."nama_subkegiatan",
  "keterangan" = EXCLUDED."keterangan";

SELECT setval(pg_get_serial_sequence('"public"."renstra_subkegiatan_prioritas"', 'id'), coalesce(max("id"), 1)) FROM "public"."renstra_subkegiatan_prioritas";
\n""")

    # 8. RENSTRA PROGRAM KEGIATAN PAGU
    f_path = os.path.join(folder, "renstra_program_kegiatan_pagu_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 8. TABEL: renstra_program_kegiatan_pagu (1535 baris: Rincian Kegiatan & Pagu 2026-2030)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_program_kegiatan_pagu" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "page_num" INTEGER,
  "kode_uraian" TEXT,
  "indikator" TEXT,
  "baseline_2024" TEXT,
  "target_2026" TEXT,
  "pagu_2026" TEXT,
  "target_2027" TEXT,
  "pagu_2027" TEXT,
  "target_2028" TEXT,
  "pagu_2028" TEXT,
  "target_2029" TEXT,
  "pagu_2029" TEXT,
  "target_2030" TEXT,
  "pagu_2030" TEXT,
  "perangkat_daerah" TEXT,
  "lokasi_keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_program_kegiatan_pagu" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_program_kegiatan_pagu" ON "public"."renstra_program_kegiatan_pagu";
CREATE POLICY "Allow anon read renstra_program_kegiatan_pagu" ON "public"."renstra_program_kegiatan_pagu" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_program_kegiatan_pagu" ON "public"."renstra_program_kegiatan_pagu";
CREATE POLICY "Allow auth write renstra_program_kegiatan_pagu" ON "public"."renstra_program_kegiatan_pagu" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'page_num', 'kode_uraian', 'indikator', 'baseline_2024', 'target_2026', 'pagu_2026', 'target_2027', 'pagu_2027', 'target_2028', 'pagu_2028', 'target_2029', 'pagu_2029', 'target_2030', 'pagu_2030', 'perangkat_daerah', 'lokasi_keterangan']
        
        # Split into batches of 250 rows for clean execution in Supabase SQL editor
        BATCH_SIZE = 250
        for b_start in range(0, len(rows), BATCH_SIZE):
            batch = rows[b_start:b_start + BATCH_SIZE]
            sql_lines.append('INSERT INTO "public"."renstra_program_kegiatan_pagu" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
            sql_lines.append('VALUES')
            value_chunks = []
            for r in batch:
                v_id = escape_sql_val(r[0], 'bigint')
                v_page = escape_sql_val(r[1], 'int')
                v_vals = [v_id, v_page] + [escape_sql_val(r[idx] if idx < len(r) else None, 'text') for idx in range(2, 17)]
                value_chunks.append(f"  ({', '.join(v_vals)})")
            sql_lines.append(",\n".join(value_chunks))
            sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "page_num" = EXCLUDED."page_num",
  "kode_uraian" = EXCLUDED."kode_uraian",
  "indikator" = EXCLUDED."indikator",
  "baseline_2024" = EXCLUDED."baseline_2024",
  "target_2026" = EXCLUDED."target_2026",
  "pagu_2026" = EXCLUDED."pagu_2026",
  "target_2027" = EXCLUDED."target_2027",
  "pagu_2027" = EXCLUDED."pagu_2027",
  "target_2028" = EXCLUDED."target_2028",
  "pagu_2028" = EXCLUDED."pagu_2028",
  "target_2029" = EXCLUDED."target_2029",
  "pagu_2029" = EXCLUDED."pagu_2029",
  "target_2030" = EXCLUDED."target_2030",
  "pagu_2030" = EXCLUDED."pagu_2030",
  "perangkat_daerah" = EXCLUDED."perangkat_daerah",
  "lokasi_keterangan" = EXCLUDED."lokasi_keterangan";
""")

        sql_lines.append("SELECT setval(pg_get_serial_sequence('\"public\".\"renstra_program_kegiatan_pagu\"', 'id'), coalesce(max(\"id\"), 1)) FROM \"public\".\"renstra_program_kegiatan_pagu\";\n")

    # 9. RENSTRA TEKNIK RUMUSAN PELAYANAN
    f_path = os.path.join(folder, "renstra_teknik_rumusan_pelayanan_rows.csv")
    if os.path.exists(f_path):
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("-- 9. TABEL: renstra_teknik_rumusan_pelayanan (1514 baris: Teknik Rumusan Pelayanan)")
        sql_lines.append("-- ==============================================================================")
        sql_lines.append("""CREATE TABLE IF NOT EXISTS "public"."renstra_teknik_rumusan_pelayanan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "page_num" INTEGER,
  "nspk_sasaran_rpjmd" TEXT,
  "tujuan" TEXT,
  "sasaran" TEXT,
  "outcome" TEXT,
  "output" TEXT,
  "indikator" TEXT,
  "program_kegiatan_subkegiatan" TEXT,
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."renstra_teknik_rumusan_pelayanan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read renstra_teknik_rumusan_pelayanan" ON "public"."renstra_teknik_rumusan_pelayanan";
CREATE POLICY "Allow anon read renstra_teknik_rumusan_pelayanan" ON "public"."renstra_teknik_rumusan_pelayanan" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write renstra_teknik_rumusan_pelayanan" ON "public"."renstra_teknik_rumusan_pelayanan";
CREATE POLICY "Allow auth write renstra_teknik_rumusan_pelayanan" ON "public"."renstra_teknik_rumusan_pelayanan" FOR ALL USING (true);
""")
        with open(f_path, "r", encoding="utf-8-sig", errors="replace") as fp:
            reader = csv.reader(fp)
            header = next(reader)
            rows = list(reader)
        
        cols = ['id', 'page_num', 'nspk_sasaran_rpjmd', 'tujuan', 'sasaran', 'outcome', 'output', 'indikator', 'program_kegiatan_subkegiatan', 'keterangan']
        
        BATCH_SIZE = 250
        for b_start in range(0, len(rows), BATCH_SIZE):
            batch = rows[b_start:b_start + BATCH_SIZE]
            sql_lines.append('INSERT INTO "public"."renstra_teknik_rumusan_pelayanan" (' + ', '.join([f'"{c}"' for c in cols]) + ')')
            sql_lines.append('VALUES')
            value_chunks = []
            for r in batch:
                v_id = escape_sql_val(r[0], 'bigint')
                v_page = escape_sql_val(r[1], 'int')
                v_vals = [v_id, v_page] + [escape_sql_val(r[idx] if idx < len(r) else None, 'text') for idx in range(2, 10)]
                value_chunks.append(f"  ({', '.join(v_vals)})")
            sql_lines.append(",\n".join(value_chunks))
            sql_lines.append("""ON CONFLICT ("id") DO UPDATE SET
  "page_num" = EXCLUDED."page_num",
  "nspk_sasaran_rpjmd" = EXCLUDED."nspk_sasaran_rpjmd",
  "tujuan" = EXCLUDED."tujuan",
  "sasaran" = EXCLUDED."sasaran",
  "outcome" = EXCLUDED."outcome",
  "output" = EXCLUDED."output",
  "indikator" = EXCLUDED."indikator",
  "program_kegiatan_subkegiatan" = EXCLUDED."program_kegiatan_subkegiatan",
  "keterangan" = EXCLUDED."keterangan";
""")

        sql_lines.append("SELECT setval(pg_get_serial_sequence('\"public\".\"renstra_teknik_rumusan_pelayanan\"', 'id'), coalesce(max(\"id\"), 1)) FROM \"public\".\"renstra_teknik_rumusan_pelayanan\";\n")

    with open(out_sql, "w", encoding="utf-8") as out_fp:
        out_fp.write("\n".join(sql_lines))
    
    print(f"Successfully generated {out_sql} with {len(sql_lines)} lines!")

if __name__ == "__main__":
    generate_sql()
