-- ==============================================================================
-- MIGRASI TABEL PERIKANAN KOTA CILEGON (PROFIL PERIKANAN KOTA CILEGON 2025)
-- Urutan 11 Tabel Teratas ke Bawah (Sesuai Urutan Carousel):
-- 1. perikanan_anggaran_program
-- 2. perikanan_armada_jenis_usaha
-- 3. perikanan_armada_kapal
-- 4. perikanan_asuransi_nelayan
-- 5. perikanan_koperasi
-- 6. perikanan_kub
-- 7. perikanan_nelayan_distribusi
-- 8. perikanan_pangkalan_nelayan
-- 9. perikanan_produksi_bulanan
-- 10. perikanan_produksi_tahunan
-- 11. perikanan_rekap_potensi
-- ==============================================================================

-- ==============================================================================
-- 1. TABEL: perikanan_anggaran_program
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_anggaran_program" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_program" VARCHAR(255) NOT NULL,
  "anggaran_2024" NUMERIC(15,2),
  "anggaran_2025" NUMERIC(15,2),
  "anggaran_2026" NUMERIC(15,2),
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_anggaran_program" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_anggaran_program" ON "public"."perikanan_anggaran_program";
CREATE POLICY "Allow anon read perikanan_anggaran_program" ON "public"."perikanan_anggaran_program" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_anggaran_program" ON "public"."perikanan_anggaran_program";
CREATE POLICY "Allow auth write perikanan_anggaran_program" ON "public"."perikanan_anggaran_program" FOR ALL USING (true);

INSERT INTO "public"."perikanan_anggaran_program" ("id", "nama_program", "anggaran_2024", "anggaran_2025", "anggaran_2026", "sumber", "created_at")
VALUES 
  (1, 'Program Perikanan Tangkap', 50000000, 85971000, 75000000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 'Program Perikanan Budidaya', 50000000, 86447000, 157500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 'Program Pengolahan dan Pemasaran Hasil Perikanan', null, 39593000, 32500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 'Program Pengawasan Sumberdaya Kelautan dan Perikanan', null, null, 7500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 'Program Perikanan Tangkap', 50000000, 85971000, 75000000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:08:32.531168+00'),
  (6, 'Program Perikanan Budidaya', 50000000, 86447000, 157500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:08:32.531168+00'),
  (7, 'Program Pengolahan dan Pemasaran Hasil Perikanan', null, 39593000, 32500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:08:32.531168+00'),
  (8, 'Program Pengawasan Sumberdaya Kelautan dan Perikanan', null, null, 7500000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:08:32.531168+00')
ON CONFLICT ("id") DO UPDATE SET
  "nama_program" = EXCLUDED."nama_program",
  "anggaran_2024" = EXCLUDED."anggaran_2024",
  "anggaran_2025" = EXCLUDED."anggaran_2025",
  "anggaran_2026" = EXCLUDED."anggaran_2026",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_anggaran_program"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_anggaran_program";


-- ==============================================================================
-- 2. TABEL: perikanan_armada_jenis_usaha
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_armada_jenis_usaha" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "jenis_usaha_penangkapan" VARCHAR(255) NOT NULL,
  "perahu_tanpa_motor" INTEGER DEFAULT 0,
  "mesin_tempel_ketingting" INTEGER DEFAULT 0,
  "kapal_motor_0_5gt" INTEGER DEFAULT 0,
  "kapal_motor_5_10gt" INTEGER DEFAULT 0,
  "kapal_30gt" INTEGER DEFAULT 0,
  "total" INTEGER DEFAULT 0,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_armada_jenis_usaha" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_armada_jenis_usaha" ON "public"."perikanan_armada_jenis_usaha";
CREATE POLICY "Allow anon read perikanan_armada_jenis_usaha" ON "public"."perikanan_armada_jenis_usaha" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_armada_jenis_usaha" ON "public"."perikanan_armada_jenis_usaha";
CREATE POLICY "Allow auth write perikanan_armada_jenis_usaha" ON "public"."perikanan_armada_jenis_usaha" FOR ALL USING (true);

INSERT INTO "public"."perikanan_armada_jenis_usaha" ("id", "no", "jenis_usaha_penangkapan", "perahu_tanpa_motor", "mesin_tempel_ketingting", "kapal_motor_0_5gt", "kapal_motor_5_10gt", "kapal_30gt", "total", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Bagan Kambang', 0, 0, 0, 0, 0, 0, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Pancing', 15, 383, 19, 5, 0, 422, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 3, 'Serok', 0, 0, 0, 0, 0, 0, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 4, 'Jaring', 0, 0, 0, 0, 0, 0, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 5, 'Bubu', 0, 0, 0, 0, 0, 0, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 6, 'Bagan Tancap', 0, 3, 0, 0, 0, 3, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "jenis_usaha_penangkapan" = EXCLUDED."jenis_usaha_penangkapan",
  "perahu_tanpa_motor" = EXCLUDED."perahu_tanpa_motor",
  "mesin_tempel_ketingting" = EXCLUDED."mesin_tempel_ketingting",
  "kapal_motor_0_5gt" = EXCLUDED."kapal_motor_0_5gt",
  "kapal_motor_5_10gt" = EXCLUDED."kapal_motor_5_10gt",
  "kapal_30gt" = EXCLUDED."kapal_30gt",
  "total" = EXCLUDED."total",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_armada_jenis_usaha"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_armada_jenis_usaha";


-- ==============================================================================
-- 3. TABEL: perikanan_armada_kapal
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_armada_kapal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kecamatan" VARCHAR(100) NOT NULL,
  "nama_pangkalan" VARCHAR(255) NOT NULL,
  "jumlah_perahu_kapal" INTEGER DEFAULT 0,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_armada_kapal" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_armada_kapal" ON "public"."perikanan_armada_kapal";
CREATE POLICY "Allow anon read perikanan_armada_kapal" ON "public"."perikanan_armada_kapal" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_armada_kapal" ON "public"."perikanan_armada_kapal";
CREATE POLICY "Allow auth write perikanan_armada_kapal" ON "public"."perikanan_armada_kapal" FOR ALL USING (true);

INSERT INTO "public"."perikanan_armada_kapal" ("id", "no", "kecamatan", "nama_pangkalan", "jumlah_perahu_kapal", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Ciwandan', 'Tanjung Leneng', 64, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Pulomerak', 'Pantai Mabak', 10, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 2, 'Pulomerak', 'Medaksa Seberang', 52, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 2, 'Pulomerak', 'Kaltek', 40, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 2, 'Pulomerak', 'Pantai Lebakgede', 16, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 2, 'Pulomerak', 'Suralaya', 67, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (7, 3, 'Grogol', 'Lelean', 54, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (8, 4, 'Citangkil', 'Tanjung Peni', 102, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (9, 5, 'Cibeber', 'Pangkalan Terate', 5, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kecamatan" = EXCLUDED."kecamatan",
  "nama_pangkalan" = EXCLUDED."nama_pangkalan",
  "jumlah_perahu_kapal" = EXCLUDED."jumlah_perahu_kapal",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_armada_kapal"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_armada_kapal";


-- ==============================================================================
-- 4. TABEL: perikanan_asuransi_nelayan
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_asuransi_nelayan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "tahun" INTEGER NOT NULL,
  "jumlah_nelayan" INTEGER,
  "sumber_anggaran" VARCHAR(255),
  "keterangan" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_asuransi_nelayan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_asuransi_nelayan" ON "public"."perikanan_asuransi_nelayan";
CREATE POLICY "Allow anon read perikanan_asuransi_nelayan" ON "public"."perikanan_asuransi_nelayan" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_asuransi_nelayan" ON "public"."perikanan_asuransi_nelayan";
CREATE POLICY "Allow auth write perikanan_asuransi_nelayan" ON "public"."perikanan_asuransi_nelayan" FOR ALL USING (true);

INSERT INTO "public"."perikanan_asuransi_nelayan" ("id", "no", "tahun", "jumlah_nelayan", "sumber_anggaran", "keterangan", "created_at")
VALUES 
  (1, 1, 2015, 415, null, 'Data historis asuransi nelayan', '2026-09-16 23:06:45.004122+00'),
  (2, 2, 2016, 311, null, 'Data historis asuransi nelayan', '2026-09-16 23:06:45.004122+00'),
  (3, 3, 2017, null, null, 'Tidak ada data', '2026-09-16 23:06:45.004122+00'),
  (4, 4, 2018, 7, null, 'Data historis asuransi nelayan', '2026-09-16 23:06:45.004122+00'),
  (5, 5, 2019, 155, null, 'Data historis asuransi nelayan', '2026-09-16 23:06:45.004122+00'),
  (6, 6, 2020, null, null, 'Tidak ada data', '2026-09-16 23:06:45.004122+00'),
  (7, 7, 2021, null, null, 'Tidak ada data', '2026-09-16 23:06:45.004122+00'),
  (8, 8, 2022, null, null, 'Tidak ada data', '2026-09-16 23:06:45.004122+00'),
  (9, 9, 2023, null, null, 'Tidak ada data', '2026-09-16 23:06:45.004122+00'),
  (10, 10, 2024, 439, 'APBD Kota Cilegon', 'Asuransi Nelayan BPAN', '2026-09-16 23:06:45.004122+00'),
  (11, 11, 2025, 439, 'APBD Kota Cilegon', 'Asuransi Nelayan BPAN', '2026-09-16 23:06:45.004122+00'),
  (12, 12, 2025, 213, 'APBD Propinsi Banten', 'Asuransi Nelayan BPAN (tambahan dari Provinsi), total 2025 = 652 nelayan', '2026-09-16 23:06:45.004122+00'),
  (13, 1, 2015, 415, null, 'Data historis asuransi nelayan', '2026-09-16 23:07:59.653786+00'),
  (14, 2, 2016, 311, null, 'Data historis asuransi nelayan', '2026-09-16 23:07:59.653786+00'),
  (15, 3, 2017, null, null, 'Tidak ada data', '2026-09-16 23:07:59.653786+00'),
  (16, 4, 2018, 7, null, 'Data historis asuransi nelayan', '2026-09-16 23:07:59.653786+00'),
  (17, 5, 2019, 155, null, 'Data historis asuransi nelayan', '2026-09-16 23:07:59.653786+00'),
  (18, 6, 2020, null, null, 'Tidak ada data', '2026-09-16 23:07:59.653786+00'),
  (19, 7, 2021, null, null, 'Tidak ada data', '2026-09-16 23:07:59.653786+00'),
  (20, 8, 2022, null, null, 'Tidak ada data', '2026-09-16 23:07:59.653786+00'),
  (21, 9, 2023, null, null, 'Tidak ada data', '2026-09-16 23:07:59.653786+00'),
  (22, 10, 2024, 439, 'APBD Kota Cilegon', 'Asuransi Nelayan BPAN', '2026-09-16 23:07:59.653786+00'),
  (23, 11, 2025, 439, 'APBD Kota Cilegon', 'Asuransi Nelayan BPAN', '2026-09-16 23:07:59.653786+00'),
  (24, 12, 2025, 213, 'APBD Propinsi Banten', 'Asuransi Nelayan BPAN (tambahan dari Provinsi),  total 2025 = 652 nelayan', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "tahun" = EXCLUDED."tahun",
  "jumlah_nelayan" = EXCLUDED."jumlah_nelayan",
  "sumber_anggaran" = EXCLUDED."sumber_anggaran",
  "keterangan" = EXCLUDED."keterangan";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_asuransi_nelayan"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_asuransi_nelayan";


-- ==============================================================================
-- 5. TABEL: perikanan_koperasi
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_koperasi" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kota" VARCHAR(100) DEFAULT 'Cilegon',
  "nama_koperasi" VARCHAR(255) NOT NULL,
  "nik" VARCHAR(50),
  "alamat" TEXT,
  "ketua" VARCHAR(150),
  "no_telp" VARCHAR(100),
  "jumlah_anggota" INTEGER DEFAULT 0,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_koperasi" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_koperasi" ON "public"."perikanan_koperasi";
CREATE POLICY "Allow anon read perikanan_koperasi" ON "public"."perikanan_koperasi" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_koperasi" ON "public"."perikanan_koperasi";
CREATE POLICY "Allow auth write perikanan_koperasi" ON "public"."perikanan_koperasi" FOR ALL USING (true);

INSERT INTO "public"."perikanan_koperasi" ("id", "no", "kota", "nama_koperasi", "nik", "alamat", "ketua", "no_telp", "jumlah_anggota", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Cilegon', 'KOPERASI KONSUMEN NELAYAN TANJUNG PENI', '36720810047600000', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Ibrahim', '087871170310, 087771271327', 206, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Cilegon', 'KOPERASI NELAYAN TANJUNG HARAPAN JAYA', null, 'Link. Rombongan RT. 01/01, Kelurahan Kepuh, Ciwandan', 'Ajat', '0858-8840-8496', 45, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 3, 'Cilegon', 'KOPERASI NELAYAN SAMUDERA BIRU', null, 'Link Baru Kelurahan Kebon Dalem Kecamatan Purwakarta', 'Azis Sanjaya', '0877-7117-0405', 25, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kota" = EXCLUDED."kota",
  "nama_koperasi" = EXCLUDED."nama_koperasi",
  "nik" = EXCLUDED."nik",
  "alamat" = EXCLUDED."alamat",
  "ketua" = EXCLUDED."ketua",
  "no_telp" = EXCLUDED."no_telp",
  "jumlah_anggota" = EXCLUDED."jumlah_anggota",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_koperasi"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_koperasi";


-- ==============================================================================
-- 6. TABEL: perikanan_kub (KELOMPOK USAHA BERSAMA NELAYAN)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_kub" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kota" VARCHAR(100) DEFAULT 'Cilegon',
  "nama_kub" VARCHAR(255) NOT NULL,
  "alamat" TEXT,
  "ketua" VARCHAR(150),
  "no_telp" VARCHAR(100),
  "jumlah_anggota" INTEGER DEFAULT 0,
  "status" VARCHAR(50) DEFAULT 'Aktif',
  "kelas_kub" VARCHAR(50) DEFAULT 'Pemula',
  "bantuan_pernah_diterima" TEXT,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_kub" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_kub" ON "public"."perikanan_kub";
CREATE POLICY "Allow anon read perikanan_kub" ON "public"."perikanan_kub" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_kub" ON "public"."perikanan_kub";
CREATE POLICY "Allow auth write perikanan_kub" ON "public"."perikanan_kub" FOR ALL USING (true);

INSERT INTO "public"."perikanan_kub" ("id", "no", "kota", "nama_kub", "alamat", "ketua", "no_telp", "jumlah_anggota", "status", "kelas_kub", "bantuan_pernah_diterima", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Cilegon', 'KUB BAHARI KALTEK', 'Link. Kaltek, Kel. Tamansari, Kec. Pulomerak', 'Rahmat Hidayat', '+6285217675630', 12, 'Aktif', 'Pemula', 'Mesin Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Cilegon', 'KUB JAYA BAHARI', 'Link. Medaksa Sebrang RT/RW 05/05 Kel. Tamansari, Kec. Pulomerak', 'Bukhori Muslim', null, 14, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 3, 'Cilegon', 'KUB PANDAN WANGI', 'Link. Medaksa Sebrang RT/RW 05/05 Kel. Tamansari, Kec. Pulomerak', 'Jajang Suryana', '085210632571', 10, 'Aktif', 'Pemula', 'Pancing Rawai Dasar, Cool Box', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 4, 'Cilegon', 'KUB MEDAKSA BAHARI', 'Link. Medaksa Sebrang RT/RW 05/05, Kelurahan Tamansari, Kecamatan Pulomerak', 'Asdik Priyatno', '087880854408', 16, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 5, 'Cilegon', 'KUB MABAK RAYA', 'Link. Mabak RT/RW 07/05, Kel. Mekarsari, Kec. Pulomerak', 'Ade Hidayat', '+6287777067808', 13, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 6, 'Cilegon', 'KUB RATU PANTAI', 'Link. Mabak RT/RW 07/05, Kel. Mekarsari, Kec. Pulomerak', 'Amar', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (7, 7, 'Cilegon', 'KUB BAHARI BERSAMA', 'Kelurahan Rawa Arum Kec. Grogol Kota Cilegon', 'Supriyatno', '087878882131', 10, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (8, 8, 'Cilegon', 'KUB BINTANG LAUT', 'Kelurahan Rawa Arum Kec. Grogol Kota Cilegon', 'Rohili', '082213451235', 15, 'Aktif', 'Pemula', 'Mesin Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (9, 9, 'Cilegon', 'KUB NELAYAN MANDIRI', 'Kelurahan Rawa Arum Kec. Grogol Kota Cilegon', 'Arip', '089527085698', 12, 'Aktif', 'Pemula', 'Mesin Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (10, 10, 'Cilegon', 'KUB BAHARI SEJAHTERA LELEAN', 'Kelurahan Rawa Arum Kec. Grogol Kota Cilegon', 'Husnaeni', '085920162919', 10, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (11, 11, 'Cilegon', 'KUB SEJAHTERA MANDIRI', 'Kelurahan Kedaleman Kec. Cibeber Kota Cilegon', 'Madsikin', null, 10, 'Aktif', 'Pemula', 'Mesin Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (12, 12, 'Cilegon', 'KUB MINA ARUM BAHARI', 'Kelurahan Rawa Arum Kec. Grogol Kota Cilegon', 'Hudeli', '081906323907', 10, 'Aktif', 'Pemula', 'Pump', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (13, 13, 'Cilegon', 'KUB PANCURAN JAYA', 'Kelurahan Suralaya Kec. Pulomerak Kota Cilegon', 'Husen', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (14, 14, 'Cilegon', 'KUB LAYANG SATU', 'Kelurahan Warna Sari Kec. Citangkil Kota Cilegon', 'Madroni', null, 10, 'Aktif', 'Pemula', 'Pump', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (15, 15, 'Cilegon', 'KUB KETAPANG', 'Link. SDM Laharmas, Kec. Pulomerak', 'Ujang Sumantri', null, 12, 'Aktif', 'Pemula', 'Pancing Rawai Dasar', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (16, 16, 'Cilegon', 'KUB GUNUNG BAHARI', 'Link. Medaksa Seberang, Rt. 05/05, Kel. Tamansari, Kec. Pulomerak', 'Nurhaman', null, 14, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (17, 17, 'Cilegon', 'KUB BINTANG TIMUR MAKMUR', 'Link. Pancuran RT/RW 03/03 Kel. Suralaya Kec. Pulomerak', 'Mamin', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (18, 18, 'Cilegon', 'KUB ALAM SAMUDERA', 'Link. Pancuran RT/RW 04/02 Kel. Suralaya Kec. Pulomerak', 'Hasni', null, 11, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (19, 19, 'Cilegon', 'KUB KALTEK', 'Link. Bumi Waras Rt. 05/03, Kel. Tamansari, Kec. Pulomerak', 'Yoyok Subagio', '+6281318164923', 14, 'Aktif', 'Pemula', 'Mesin Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (20, 20, 'Cilegon', 'KUB SINAR BAHARI', 'Link. Pancuran RT/RW 03/03 Kel. Suralaya Kec. Pulomerak', 'Jaenal Abidin', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (21, 21, 'Cilegon', 'KUB BAHARI SELAT SUNDA', 'Link. Gerem Raya, Rt.01/04, Kel. Gerem, Kec. Grogol', 'A. Junaedi', null, 10, 'Aktif', 'Pemula', 'Perahu Ketingting', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (22, 22, 'Cilegon', 'KUB SAMUDERA BIRU', 'Link. Baru Rt. 01/03, Kel. Kebondalem, Kec. Purwakarta', 'Mahfud', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (23, 23, 'Cilegon', 'KUB NUSA MANDALA', 'Kel. Mekarsari, Kecamatan Pulomerak', 'Enday Munandar', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (24, 24, 'Cilegon', 'KUB TANJUNG HARAPAN', 'Link. Rombongan RT. 01/01, Kelurahan Kepuh, Ciwandan', 'Syahroni', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (25, 25, 'Cilegon', 'KUB HARAPAN JAYA', 'Link. Rombongan RT. 01/01, Kelurahan Kepuh, Ciwandan', 'Syakroni', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (26, 26, 'Cilegon', 'KUB TANJUNG CAYUR', 'Link. Rombongan RT. 01/01, Kelurahan Kepuh, Ciwandan', 'Tajudin', null, 17, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (27, 27, 'Cilegon', 'KUB MINA TANJUNG PENI', 'Jl. Amerika III Tanjung Peni, Kel. Warnasasri, Citangkil', 'Robani', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (28, 28, 'Cilegon', 'KUB KERAPU MACAN', 'Jl. Amerika III Tanjung Peni, Kel. Warnasasri, Citangkil', 'Khaerudin', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (29, 29, 'Cilegon', 'KUB PUTRA TANJUNG I', 'Link. Kelelet, Rt. 03/03, Kel. Warnasari, Citangkil', 'Abdullah', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (30, 30, 'Cilegon', 'KUB LAYANG EMPAT', 'Link. Temu Putih, Rt. 02/02, Kel. Ciwaduk, Cilegon', 'Yahya Affandi', null, 16, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (31, 31, 'Cilegon', 'KUB MEKAR WANGI', 'Link. Medaksa Sebrang, Rt. 05/05, Kel. Tamansari, Pulomerak', 'Imam Rohim', '085211238253', 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (32, 32, 'Cilegon', 'KUB PUTERA SAMUDERA', 'Link. Pancuran RT/RW 03/03 Kel. Suralaya Kec. Pulomerak', 'Hawasi', null, 11, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (33, 33, 'Cilegon', 'KUB MITRA BAHARI', 'Link. Kembang Kuning RT/RW 02/04 Kel. Suralaya Kec. Pulomerak', 'Hendra Wanto', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (34, 34, 'Cilegon', 'KUB GUNUNG SAMUDERA', 'Link. Pancuran RT/RW 03/03 Kel. Suralaya Kec. Pulomerak', 'Heriyanto', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (35, 35, 'Cilegon', 'KUB BERKAH BAHARI', 'Link. Pancuran RT/RW 03/03 Kel. Suralaya Kec. Pulomerak', 'Jaka Sutomo', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (36, 36, 'Cilegon', 'KUB KELAPA TUJUH', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Eri Sanuri', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (37, 37, 'Cilegon', 'KUB BUAH KEPUDANG', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Madyumi', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (38, 38, 'Cilegon', 'KUB WATU IRENG', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Asmad', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (39, 39, 'Cilegon', 'KUB PINGGIR JINTUNG', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Jasmiri', '+6287875349676', 11, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (40, 40, 'Cilegon', 'KUB KALI KEMBU', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Bambang', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (41, 41, 'Cilegon', 'KUB PELANDAU', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Mad Sufi', null, 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (42, 42, 'Cilegon', 'KUB GUNUNG SALAK', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Suwiro', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (43, 43, 'Cilegon', 'KUB SURAMINA BAHARI', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Habib', null, 11, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (44, 44, 'Cilegon', 'KUB TANJUT POEJUT', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Sanwani', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (45, 45, 'Cilegon', 'KUB KALI KAHAL', 'Jln. Raya PLTU Suralaya Kel. Suralaya Kec. Pulomerak', 'Mamat', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (46, 46, 'Cilegon', 'KUB MINA BAHARI', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Sukarti', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (47, 47, 'Cilegon', 'KUB AKA ABADI', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Agus Rohmadi', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (48, 48, 'Cilegon', 'KUB LINTAS PULAU', 'Link. Warung Luwet Kel. Samangraya Kec. Citangkil', 'Rahmat Apip', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (49, 49, 'Cilegon', 'KUB BUBU BAHARI JAYA', 'Kel. Rawa Arum Kec. Grogol', 'Jupri', '081241205877', 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (50, 50, 'Cilegon', 'KUB PUTRA BAHARI LELEAN', 'Kel. Rawa Arum Kec. Grogol', 'Karna', '08128579371', 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (51, 51, 'Cilegon', 'KUB BINA SEJAHTERA LELEAN', 'Kel. Rawa Arum Kec. Grogol', 'M. Sayuti', '085921736506', 12, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (52, 52, 'Cilegon', 'KUB SRI GOBEL', 'Kel. Rawa Arum Kec. Grogol', 'Asri Darmawan', '087871350420', 11, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (53, 53, 'Cilegon', 'KUB BEBUAR JAYA', 'Link. Tegal Padang Rt. 01/03, Kel. Kebondalem, Kec. Purwakarta', 'Sumanto Arief', null, 14, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (54, 54, 'Cilegon', 'KUB KARANG TANJUNG', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Masri Bahrudin', null, 14, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (55, 55, 'Cilegon', 'KUB BERKAH MANDIRI', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Mulhatulloh', null, 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (56, 56, 'Cilegon', 'KUB AKUR ABADI', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Jasmani', null, 14, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (57, 57, 'Cilegon', 'KUB TANJUNG CEMARA', 'Jl. Amerika II Tanjung Peni, Kel. Warnasasri, Citangkil', 'Ahmad Safari', null, 13, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (58, 58, 'Cilegon', 'KUB BAHARI SEBRANG LELEAN', 'Kel. Gerem Kec. Grogol', 'Babay Efendi', '081317606456', 10, 'Aktif', 'Pemula', null, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kota" = EXCLUDED."kota",
  "nama_kub" = EXCLUDED."nama_kub",
  "alamat" = EXCLUDED."alamat",
  "ketua" = EXCLUDED."ketua",
  "no_telp" = EXCLUDED."no_telp",
  "jumlah_anggota" = EXCLUDED."jumlah_anggota",
  "status" = EXCLUDED."status",
  "kelas_kub" = EXCLUDED."kelas_kub",
  "bantuan_pernah_diterima" = EXCLUDED."bantuan_pernah_diterima",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_kub"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_kub";


-- ==============================================================================
-- 7. TABEL: perikanan_nelayan_distribusi
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_nelayan_distribusi" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kecamatan" VARCHAR(100) NOT NULL,
  "jumlah_kecamatan" INTEGER DEFAULT 0,
  "kelurahan" VARCHAR(100) NOT NULL,
  "jumlah_nelayan" INTEGER DEFAULT 0,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_nelayan_distribusi" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_nelayan_distribusi" ON "public"."perikanan_nelayan_distribusi";
CREATE POLICY "Allow anon read perikanan_nelayan_distribusi" ON "public"."perikanan_nelayan_distribusi" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_nelayan_distribusi" ON "public"."perikanan_nelayan_distribusi";
CREATE POLICY "Allow auth write perikanan_nelayan_distribusi" ON "public"."perikanan_nelayan_distribusi" FOR ALL USING (true);

INSERT INTO "public"."perikanan_nelayan_distribusi" ("id", "kecamatan", "jumlah_kecamatan", "kelurahan", "jumlah_nelayan", "tahun", "sumber", "created_at")
VALUES 
  (1, 'Pulomerak', 306, 'Suralaya', 126, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 'Pulomerak', 306, 'Lebak Gede', 24, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 'Pulomerak', 306, 'Mekarsari', 65, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 'Pulomerak', 306, 'Tamansari', 91, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 'Grogol', 133, 'Gerem', 47, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 'Grogol', 133, 'Rawa Arum', 83, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (7, 'Grogol', 133, 'Grogol', 3, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (8, 'Purwakarta', 19, 'Kebon Dalem', 15, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (9, 'Purwakarta', 19, 'Kota Bumi', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (10, 'Purwakarta', 19, 'Pabean', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (11, 'Purwakarta', 19, 'Purwakarta', 0, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (12, 'Cilegon', 7, 'Ciwaduk', 1, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (13, 'Cilegon', 7, 'Bendungan', 4, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (14, 'Cilegon', 7, 'Ketileng', 1, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (15, 'Cilegon', 7, 'Bagendung', 1, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (16, 'Cibeber', 20, 'Kedaleman', 16, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (17, 'Cibeber', 20, 'Cibeber', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (18, 'Cibeber', 20, 'Kalitimbang', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (19, 'Citangkil', 120, 'Warnasari', 26, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (20, 'Citangkil', 120, 'Semang Raya', 15, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (21, 'Citangkil', 120, 'LebakDenok', 12, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (22, 'Citangkil', 120, 'Taman Baru', 3, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (23, 'Citangkil', 120, 'Citangkil', 15, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (24, 'Citangkil', 120, 'Kebonsari', 40, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (25, 'Citangkil', 120, 'Deringo', 9, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (26, 'Ciwandan', 108, 'Kepuh', 42, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (27, 'Ciwandan', 108, 'Gunung Sugih', 9, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (28, 'Ciwandan', 108, 'Tegal Ratu', 26, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (29, 'Ciwandan', 108, 'Kubang Sari', 8, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (30, 'Ciwandan', 108, 'Banjarnegara', 9, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (31, 'Ciwandan', 108, 'Randa Kari', 14, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (32, 'Jombang', 10, 'Jombang Wetan', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (33, 'Jombang', 10, 'Gedong Dalem', 2, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (34, 'Jombang', 10, 'Sukmajaya', 3, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (35, 'Jombang', 10, 'Panggung Rawi', 3, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "kecamatan" = EXCLUDED."kecamatan",
  "jumlah_kecamatan" = EXCLUDED."jumlah_kecamatan",
  "kelurahan" = EXCLUDED."kelurahan",
  "jumlah_nelayan" = EXCLUDED."jumlah_nelayan",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_nelayan_distribusi"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_nelayan_distribusi";


-- ==============================================================================
-- 8. TABEL: perikanan_pangkalan_nelayan
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_pangkalan_nelayan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "kecamatan" VARCHAR(100) NOT NULL,
  "nama_pangkalan" VARCHAR(255) NOT NULL,
  "asal_nelayan" TEXT,
  "jumlah_nelayan" INTEGER DEFAULT 0,
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_pangkalan_nelayan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_pangkalan_nelayan" ON "public"."perikanan_pangkalan_nelayan";
CREATE POLICY "Allow anon read perikanan_pangkalan_nelayan" ON "public"."perikanan_pangkalan_nelayan" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_pangkalan_nelayan" ON "public"."perikanan_pangkalan_nelayan";
CREATE POLICY "Allow auth write perikanan_pangkalan_nelayan" ON "public"."perikanan_pangkalan_nelayan" FOR ALL USING (true);

INSERT INTO "public"."perikanan_pangkalan_nelayan" ("id", "no", "kecamatan", "nama_pangkalan", "asal_nelayan", "jumlah_nelayan", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Ciwandan', 'Tanjung Leneng', 'Ciwandan', 72, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Pulomerak', 'Pantai Mabak', 'Mekarsari', 65, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 2, 'Pulomerak', 'Medaksa Seberang', 'Tamansari', 76, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 2, 'Pulomerak', 'Kaltek', 'Tamansari', 15, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 2, 'Pulomerak', 'Lebak Gede', 'Lebakgede', 24, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 2, 'Pulomerak', 'Suralaya', 'Suralaya', 144, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (7, 3, 'Grogol', 'Lelean', 'Gerem', 110, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (8, 4, 'Citangkil', 'Tanjung Peni', 'Citangkil, Ciwandan, Purwakarta, Cilegon, Jombang', 191, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (9, 5, 'Cibeber', 'Pangkalan Terate', null, 18, 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "kecamatan" = EXCLUDED."kecamatan",
  "nama_pangkalan" = EXCLUDED."nama_pangkalan",
  "asal_nelayan" = EXCLUDED."asal_nelayan",
  "jumlah_nelayan" = EXCLUDED."jumlah_nelayan",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_pangkalan_nelayan"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_pangkalan_nelayan";


-- ==============================================================================
-- 9. TABEL: perikanan_produksi_bulanan
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_produksi_bulanan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tahun" INTEGER DEFAULT 2025,
  "jenis_komoditas" VARCHAR(255) NOT NULL,
  "januari_kg" NUMERIC(15,3) DEFAULT 0,
  "februari_kg" NUMERIC(15,3) DEFAULT 0,
  "maret_kg" NUMERIC(15,3) DEFAULT 0,
  "april_kg" NUMERIC(15,3) DEFAULT 0,
  "mei_kg" NUMERIC(15,3) DEFAULT 0,
  "juni_kg" NUMERIC(15,3) DEFAULT 0,
  "juli_kg" NUMERIC(15,3) DEFAULT 0,
  "agustus_kg" NUMERIC(15,3) DEFAULT 0,
  "september_kg" NUMERIC(15,3) DEFAULT 0,
  "oktober_kg" NUMERIC(15,3) DEFAULT 0,
  "november_kg" NUMERIC(15,3) DEFAULT 0,
  "desember_kg" NUMERIC(15,3) DEFAULT 0,
  "total_produksi_kg" NUMERIC(15,3) DEFAULT 0,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_produksi_bulanan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_produksi_bulanan" ON "public"."perikanan_produksi_bulanan";
CREATE POLICY "Allow anon read perikanan_produksi_bulanan" ON "public"."perikanan_produksi_bulanan" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_produksi_bulanan" ON "public"."perikanan_produksi_bulanan";
CREATE POLICY "Allow auth write perikanan_produksi_bulanan" ON "public"."perikanan_produksi_bulanan" FOR ALL USING (true);

INSERT INTO "public"."perikanan_produksi_bulanan" ("id", "tahun", "jenis_komoditas", "januari_kg", "februari_kg", "maret_kg", "april_kg", "mei_kg", "juni_kg", "juli_kg", "agustus_kg", "september_kg", "oktober_kg", "november_kg", "desember_kg", "total_produksi_kg", "sumber", "created_at")
VALUES 
  (1, 2025, 'Ikan Air Tawar (Budidaya)', 31422.000, 29462.000, 29720.000, 27570.000, 29656.000, 33210.000, 35550.000, 32365.000, 30126.000, 24811.000, 22810.000, 22442.000, 349144.000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2025, 'Hasil Tangkapan di Laut', 11464.000, 15834.000, 17476.000, 23582.000, 22654.000, 23167.000, 24654.000, 22476.000, 25732.000, 22597.000, 12435.000, 7965.000, 230036.000, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "tahun" = EXCLUDED."tahun",
  "jenis_komoditas" = EXCLUDED."jenis_komoditas",
  "januari_kg" = EXCLUDED."januari_kg",
  "februari_kg" = EXCLUDED."februari_kg",
  "maret_kg" = EXCLUDED."maret_kg",
  "april_kg" = EXCLUDED."april_kg",
  "mei_kg" = EXCLUDED."mei_kg",
  "juni_kg" = EXCLUDED."juni_kg",
  "juli_kg" = EXCLUDED."juli_kg",
  "agustus_kg" = EXCLUDED."agustus_kg",
  "september_kg" = EXCLUDED."september_kg",
  "oktober_kg" = EXCLUDED."oktober_kg",
  "november_kg" = EXCLUDED."november_kg",
  "desember_kg" = EXCLUDED."desember_kg",
  "total_produksi_kg" = EXCLUDED."total_produksi_kg",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_produksi_bulanan"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_produksi_bulanan";


-- ==============================================================================
-- 10. TABEL: perikanan_produksi_tahunan
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_produksi_tahunan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tahun" INTEGER NOT NULL,
  "produksi_tangkap_ton" NUMERIC(12,3) DEFAULT 0,
  "produksi_budidaya_ton" NUMERIC(12,3) DEFAULT 0,
  "total_produksi_ton" NUMERIC(12,3) DEFAULT 0,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_produksi_tahunan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_produksi_tahunan" ON "public"."perikanan_produksi_tahunan";
CREATE POLICY "Allow anon read perikanan_produksi_tahunan" ON "public"."perikanan_produksi_tahunan" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_produksi_tahunan" ON "public"."perikanan_produksi_tahunan";
CREATE POLICY "Allow auth write perikanan_produksi_tahunan" ON "public"."perikanan_produksi_tahunan" FOR ALL USING (true);

INSERT INTO "public"."perikanan_produksi_tahunan" ("id", "tahun", "produksi_tangkap_ton", "produksi_budidaya_ton", "total_produksi_ton", "sumber", "created_at")
VALUES 
  (1, 2020, 219.300, 230.000, 449.300, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2021, 238.400, 262.000, 500.400, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 2022, 241.900, 354.600, 596.500, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 2023, 240.130, 371.630, 611.760, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 2024, 237.200, 360.500, 597.700, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 2025, 238.864, 361.455, 600.319, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "tahun" = EXCLUDED."tahun",
  "produksi_tangkap_ton" = EXCLUDED."produksi_tangkap_ton",
  "produksi_budidaya_ton" = EXCLUDED."produksi_budidaya_ton",
  "total_produksi_ton" = EXCLUDED."total_produksi_ton",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_produksi_tahunan"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_produksi_tahunan";


-- ==============================================================================
-- 11. TABEL: perikanan_rekap_potensi
-- ==============================================================================
CREATE TABLE IF NOT EXISTS "public"."perikanan_rekap_potensi" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no" INTEGER,
  "uraian" VARCHAR(255) NOT NULL,
  "jumlah" VARCHAR(100) NOT NULL,
  "jumlah_teks" VARCHAR(100),
  "tahun" INTEGER DEFAULT 2025,
  "sumber" VARCHAR(255) DEFAULT 'Profil Perikanan Kota Cilegon 2025',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "public"."perikanan_rekap_potensi" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read perikanan_rekap_potensi" ON "public"."perikanan_rekap_potensi";
CREATE POLICY "Allow anon read perikanan_rekap_potensi" ON "public"."perikanan_rekap_potensi" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow auth write perikanan_rekap_potensi" ON "public"."perikanan_rekap_potensi";
CREATE POLICY "Allow auth write perikanan_rekap_potensi" ON "public"."perikanan_rekap_potensi" FOR ALL USING (true);

INSERT INTO "public"."perikanan_rekap_potensi" ("id", "no", "uraian", "jumlah", "jumlah_teks", "tahun", "sumber", "created_at")
VALUES 
  (1, 1, 'Nelayan', '723', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (2, 2, 'Koperasi Nelayan', '3', 'Koperasi', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (3, 3, 'Kelompok Nelayan (KUB)', '58', 'KUB', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (4, 4, 'Pangkalan Nelayan', '8', 'Pangkalan', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (5, 5, 'Kapal/Perahu Perikanan', '410', 'Perahu', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (6, 6, 'Alat Tangkap', '425', 'Buah', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (7, 7, 'Pembudidaya Kota Cilegon', '395', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (8, 8, 'Kelompok Pembudidaya Ikan (POKDAKAN)', '28', 'Pokdakan', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (9, 9, 'Pembudidaya Pembesaran Lele', '360', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (10, 10, 'Pembudidaya Pembenihan Lele', '30', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (11, 11, 'Luas Kolam Budidaya', '37461', 'Meter²', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (12, 12, 'Pelaku Usaha Ikan Hias', '45', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (13, 13, 'Pembudidaya Ikan Hias', '6', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (14, 14, 'Pengolah Hasil Perikanan', '131', 'Orang', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (15, 15, 'Kelompok Pengolah dan Pemasar (POKLASHAR)', '17', 'Kelompok', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (16, 16, 'Data Produksi Budidaya 2024', '360.5', 'Ton/Tahun', 2024, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (17, 17, 'Data Produksi Tangkap 2024', '237.1', 'Ton/Tahun', 2024, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (18, 18, 'Pulau', '5', 'Pulau', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00'),
  (19, 19, 'Panjang Pantai', '40.8', 'km', 2025, 'Profil Perikanan Kota Cilegon 2025', '2026-09-16 23:07:59.653786+00')
ON CONFLICT ("id") DO UPDATE SET
  "no" = EXCLUDED."no",
  "uraian" = EXCLUDED."uraian",
  "jumlah" = EXCLUDED."jumlah",
  "jumlah_teks" = EXCLUDED."jumlah_teks",
  "tahun" = EXCLUDED."tahun",
  "sumber" = EXCLUDED."sumber";

SELECT setval(pg_get_serial_sequence('"public"."perikanan_rekap_potensi"', 'id'), coalesce(max("id"), 1)) FROM "public"."perikanan_rekap_potensi";
